
name: Test Suite

on: 
  push:
    branches: [master]  # Replace with your main branch, e.g., master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12']  # Python version from your project setup

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install matplotlib
        pip install laser-learning-environment
        pip install pytest

    - name: Run tests
      run: pytest --disable-warnings -v